#------------------------------------#
#----- Alacritty configurations -----#
#------------------------------------#

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 15

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[scrolling]
history = 20000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
blur = false
option_as_alt = "both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0

# Thanks to alabaster
[colors.primary]
background = "#f7f7f7"
foreground = "#434343"

[colors.cursor]
text = "#f7f7f7"
cursor = "#434343"

[colors.normal]
black = "#000000"
red = "#aa3731"
green = "#448c27"
yellow = "#cb9000"
blue = "#325cc0"
magenta = "#7a3e9d"
cyan = "#0083b2"
white = "#bbbbbb"

[colors.bright]
black = "#777777"
red = "#f05050"
green = "#60cb00"
yellow = "#ffbc5d"
blue = "#007acc"
magenta = "#e64ce6"
cyan = "#00aacb"
white = "#ffffff"
